### ISSUE TITLE
Adding a License (License.txt)

### ISSUE THREAD

**Issue by apowellgt** [pengwyn/SentryIntegration.jl#1]
Thank you for sharing this package. We're also interested in using Sentry with Julia. Would you consider adding a license to this repository so we know how this package may be used?

**Comment by pengwyn** [comment]
Gladly! I'll add an MIT license in right away.

I haven't used this for a while, so there hasn't been any maintenance for a while. Any updates/fixes are welcome.

**Comment by apowellgt** [comment]
Thank you, very much appreciated! We'll be happy to share updates that might be useful to others.
