### ISSUE TITLE
Cannot Install via GitHub URL

### ISSUE THREAD

**Issue by alextruesdale** [pengwyn/SentryIntegration.jl#3]
**SOLVED**: I solved this after a bit of digging but will put it here in case anyone else hits the same snag.
***

I am trying the add-via-GitHub route using Julia 1.8.3 and am running into the following error:

```
pkg> add https://github.com/synchronoustechnologies/SentryIntegration.jl.git
```

```
ERROR: Unsatisfiable requirements detected for package AutoParameters [2688778c]:
 AutoParameters [2688778c] log:
 ├─AutoParameters [2688778c] has no known versions!
 └─restricted to versions * by SentryIntegration [0c0dc41a] — no versions left
   └─SentryIntegration [0c0dc41a] log:
     ├─possible versions are: 0.4.8 or uninstalled
     └─SentryIntegration [0c0dc41a] is fixed to version 0.4.8
```

This is happening because [AutoParameters](https://github.com/pengwyn/AutoParameters.jl) is another package by @pengwyn (thank you for your time spent writing these!) that is not in the official Julia package registry. Fixing the issue is easy. Simply install AutoParameters via GitHub first, then the SentryIntegration installation works without issue.

```
pkg> add https://github.com/pengwyn/AutoParameters.jl
```

```
pkg> add https://github.com/synchronoustechnologies/SentryIntegration.jl.git
```

**Comment by pengwyn** [comment]
Oh I see! Yes this dependency on AutoParameters is a bit bad I think, mostly because I suspect there are now better ways. I should really get rid of that so this package is more self-contained.

PRs welcome! Or I might try and have a go at this myself sometime...
